### ISSUE TITLE
Have you looked into expanding this for the Nest Cam?

### ISSUE THREAD

**Issue by alberttwong** [mochman/MMM-Nest#12]
Just curious just it seems like it's the same API call get the cam stream.   If not, I might borrow your code to build it.

**Comment by alberttwong** [comment]
https://nestdevelopers.io/t/using-nest-weave-to-connect-the-nest-cam-and-laptop/339/6

**Comment by alberttwong** [comment]
Problem is that it seems that Nest won't allow any of their private, protected or public streams in an iFrame.

I get errors like

```
Load denied by X-Frame-Options: https://home.nest.com/cameras/CjZUdXEtMy1xa3R0YjMzYmdpb3Y4WmM4ZkszRS1MUUhuQndPV05fVDNlRVRqWXJNYTFTS3RDRkESFnMwbUstYnA1VlZhT1dnTnpzcXJwNEEaNjZveVdXX1RodUNHcWJSb2Q0ZkNIWjFKMjJCV1JkN0RFSldBbVBLd3pYVGllODFqODFjaFAzUQ?auth=c.4y5J7z5TkYYT9s3xtVSy1BFBvqLAFBFn6OVNDD8HqgKuTS7dxrHKjfZFq0alZIVXXRoAdTS6IdcsjinwqUj4Cz4k0GzTRl9CZdrg7B0NVtxrQZuKsCLhVW0eUQtKXhZ87C97gCsdxLIZr3wu does not permit framing.
```

**Comment by alberttwong** [comment]
More about the ask.   You can get this working if you switch all your cams to public. I'm asking nest if there are other options. https://nestdevelopers.io/t/is-there-a-way-to-get-cam-streams-in-an-iframe/813

**Comment by mochman** [comment]
Did you change your nest permissions to allow read access to the camera?
