### ISSUE TITLE
font issue

### ISSUE THREAD

**Issue by alberttwong** [mochman/MMM-Nest#13]
```
downloadable font: download failed (font-family: "akkuratregular" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: http://10.0.1.24:8080/fonts/Akkurat/akkurat-webfont.woff
```

**Comment by mochman** [comment]
Are you sure you have the font installed?  It doesn't come with the program.  You have to get it and put it in the Akkurat/font/ folder.

**Comment by alberttwong** [comment]
Do you know where to get it or just google it?

**Comment by mochman** [comment]
Akkurat is a licensed font.  As such it is not included with this module.  You shouldn't need it -- this module will fall back to Roboto, but if you want the display to look as Nest-like as possible, accquire the web-font Akkurat and place in MagicMirror's /fonts/ folder, in a subfolder named "Akkurat". Be sure to name your file akkurat-webfont.woff or akkurat-webfont.woff2 depending on what format you have.

Where are you seeing your error?  I have run this module with and without the font.  If you can't find the font, you can edit the .css file to get rid of the Akkurat font.

**Comment by alberttwong** [comment]
I see it in the logs.
