### ISSUE TITLE
Feature / Improvement

### ISSUE THREAD

**Issue by frekel** [mochman/MMM-Nest#2]
I have add the degrees/farhenheit sign next the the temp:

```
if (this.config.units === 'imperial') {
    this.ambientTemp = data.thermostats[keyVar].ambient_temperature_f + " F";
    this.targetTemp = data.thermostats[keyVar].target_temperature_f + " F";
} else {
    this.ambientTemp = data.thermostats[keyVar].ambient_temperature_c +  "&deg;";
    this.targetTemp = data.thermostats[keyVar].target_temperature_c +  "&deg;";
}
```

**Comment by mochman** [comment]
Looks good, but I'm going for a look similar to the Nest display.  I don't know about Celcius, but there is no degree symbol nor "F" next to the temperature when using Fahrenheit.

**Comment by frekel** [comment]
If you are going for a similar look as the Nest display, then this request isn't going to happen :)
My Nest is set to Celcius and there is also only a number (and no &deg; sign).
