### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by michael5r** [mochman/MMM-Nest#20]
@mochman Seeing that it didn't look like this module was still being maintained, I forked your repo here:
https://github.com/michael5r/MMM-Nest

and then rewrote all the code to fix bugs, provide more configuration options, add new designs, etc. 

If you're still maintaining this module, I'm fine with opening a PR in this repo to add all my code - otherwise, let me know, and I'll remove my fork and just create a new module that I'll maintain going forward.

Thanks!

**Comment by michael5r** [comment]
Nvm - have several more things I want to add, so it's easier to just create a new module.

**Comment by mochman** [comment]
Sounds good.  I've not had too much time to keep this module up to date.
