### ISSUE TITLE
Heat & Cool Mode

### ISSUE THREAD

**Issue by BDriscal** [mochman/MMM-Nest#3]
Please look into this so it can display this mode.

**Comment by mochman** [comment]
I made a new branch called heat_cool_setting.  I don't have my setup here to test it out right now, would you mind pulling that branch and seeing if it works the way you want it?

**Comment by mochman** [comment]
I merged the new heat/cool mode with the master if you want to pull that one.

**Comment by BDriscal** [comment]
Any luck with showing both the heat and the cool setting at the same time
like it does on the app?

**Comment by mochman** [comment]
Should be. Its on the master branch if you want to check it out.
