### ISSUE TITLE
Receiving a "Failed to Load Resource" Error and a Black Screen

### ISSUE THREAD

**Issue by LoopyFoot** [mochman/MMM-Nest#6]
When I load my MagicMirror, I only receive a blank black screen, and the error is as follows:

```
Load script: modules/MMM-Nest//MMM-Nest.js
Failed to load resource: the server responded with a status of 404 (Not Found)
```

What may be causing this error?  

My account has 3 Nest's tied to it.  I should have the correct token, and my config.js appears to be correct.

Could it be a Port issue?  Any ideas are appreciated!

**Comment by mochman** [comment]
Where exactly are you seeing this error?  In the console logs or directly from MagicMirror?
Just to make sure your pi is able to get to nest's website, can you try going to 
https://developer-api.nest.com/devices?auth=YOUR_TOKEN from your pi and see if that works?

**Comment by LoopyFoot** [comment]
I am seeing the error when I run the mirror in developer mode with: `npm start dev`

The following is what the developer-api.nest website looks like when I use my token.  So it appears to be working with the API correctly?  Is it because I have three thermostats on the account?:
`{"thermostats":{"zgyrQMISWRm5Qnu5NwXJz7vHuRe4XlBw":{"humidity":60,"locale":"en-US","temperature_scale":"F","is_using_emergency_heat":false,"has_fan":true,"software_version":"5.5.1-6","has_leaf":true,"where_id":"LbcXbJmkMi8k6fCOm0EbsGyQ3CmZgyN-1isqiwLMMsS_-O0iGrykgA","device_id":"zgyrQMISWRm5Qnu5NwXJz7vHuRe4XlBw","name":"Dining Room (Nest)","can_heat":true,"can_cool":true,"target_temperature_c":24.0,"target_temperature_f":76,"target_temperature_high_c":24.0,"target_temperature_high_f":75,"target_temperature_low_c":20.0,"target_temperature_low_f":68,"ambient_temperature_c":23.0,"ambient_temperature_f":73,"away_temperature_high_c":24.0,"away_temperature_high_f":76,"away_temperature_low_c":12.5,"away_temperature_low_f":55,"is_locked":false,"locked_temp_min_c":20.0,"locked_temp_min_f":68,"locked_temp_max_c":22.0,"locked_temp_max_f":72,"structure_id":"Nt_KFAqTwK4VNT0l9r77Z_s44CvIOxhaAp6NpVXXKQvXjxsd1wmZBA","fan_timer_active":false,"fan_timer_timeout":"1970-01-01T00:00:00.000Z","hvac_mode":"off","name_long":"Dining Room Thermostat (Nest)","is_online":true,"last_connection":"2016-10-05T14:30:39.056Z","hvac_state":"off"},"zgyrQMISWRnEoYwCmWX7g7vHuRe4XlBw":{"humidity":60,"locale":"en-GB","temperature_scale":"F","is_using_emergency_heat":false,"has_fan":true,"software_version":"5.5.1-6","has_leaf":true,"where_id":"LbcXbJmkMi8k6fCOm0EbsGyQ3CmZgyN-1isqiwLMMsQ1BodGkLhSDg","device_id":"zgyrQMISWRnEoYwCmWX7g7vHuRe4XlBw","name":"Basement","can_heat":true,"can_cool":true,"target_temperature_c":24.5,"target_temperature_f":76,"target_temperature_high_c":24.0,"target_temperature_high_f":75,"target_temperature_low_c":20.0,"target_temperature_low_f":68,"ambient_temperature_c":23.5,"ambient_temperature_f":75,"away_temperature_high_c":24.0,"away_temperature_high_f":76,"away_temperature_low_c":12.5,"away_temperature_low_f":55,"is_locked":false,"locked_temp_min_c":20.0,"locked_temp_min_f":68,"locked_temp_max_c":22.0,"locked_temp_max_f":72,"structure_id":"Nt_KFAqTwK4VNT0l9r77Z_s44CvIOxhaAp6NpVXXKQvXjxsd1wmZBA","fan_timer_active":false,"fan_timer_timeout":"1970-01-01T00:00:00.000Z","hvac_mode":"off","name_long":"Basement Thermostat","is_online":true,"last_connection":"2016-10-05T14:31:03.937Z","hvac_state":"off"}}}`

**Comment by mochman** [comment]
Yeah, it definitely looks like your token is good.  

I just ran the same `dev` mode and it still work for me.  Just to be clear, your Pi is connected to the internet right?  

My module doesn't produce the error :
`Failed to load resource: the server responded with a status of 404 (Not Found)`
That looks like it could be a MagicMirror error.  Have you gotten other modules to work on your mirror?

**Comment by LoopyFoot** [comment]
Yep, my Pi is connected to the internet.

When I comment out the MMM-Nest module from my config.js, all of the other default modules load and the mirror runs properly.  But as soon as I uncomment out everything for the MMM-Nest module, I receive the black screen.

I have three Nest thermostats, so I wonder if that may be the issue?  Since it looks like this module was designed for just one thermostat?

**Comment by mochman** [comment]
The module should just take the data from your first thermostat, but the module should still load.  Would you mind commenting out your token from the config.js and see if the module loads then?

**Comment by LoopyFoot** [comment]
I see the same error as above, when I comment out my token.  

My config.js is as follows:

```
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 */

var config = {
    port: 8080,

    language: 'en',
    timeFormat: 24,
    units: 'metric',

    modules: [
        {
            module: 'alert',
        },
        {
        module: 'MMM-Nest',
        position: 'bottom_right',   
        config: {

            //token: "MY_TOKEN_IS_IN_HERE"

            }
        },      
        {
            module: 'clock',
            position: 'top_left'
        },
        {
            module: 'calendar',
            header: 'US Holidays',
            position: 'top_left',
            config: {
                calendars: [
                    {
                        symbol: 'calendar-check-o ',
                        url: 'webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics'
                    }
                ]
            }
        },


        {
            module: 'currentweather',
            position: 'top_right',
            config: {
                location: 'New York',
                locationID: '',  //ID from http://www.openweathermap.org
                appid: 'YOUR_OPENWEATHER_API_KEY'
            }
        },
        {
            module: 'weatherforecast',
            position: 'top_right',
            header: 'Weather Forecast',
            config: {
                location: 'New York',
                locationID: '5128581',  //ID from http://www.openweathermap.org
                appid: 'YOUR_OPENWEATHER_API_KEY'
            }
        },
        {
            module: 'newsfeed',
            position: 'bottom_bar',
            config: {
                feeds: [
                    {
                        title: "New York Times",
                        url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
                    }
                ],
                showSourceTitle: true,
                showPublishDate: true
            }
        },
    ]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}

```

**Comment by mochman** [comment]
I just reproduced the error.  Looks like you don't have a MMM-Nest folder.  Did you clone it in your `MagicMirror/modules` directory?

**Comment by LoopyFoot** [comment]
I ran the following, which I think is to see if the Port 8080 is open: nc -z 127.0.0.1 8080; echo $?

It returned a "1", which I think may be a failure.  I may need to figure out how to open this port?

**Comment by LoopyFoot** [comment]
MMM-Nest is in my "default" folder. Should it be somewhere else also?

**Comment by LoopyFoot** [comment]
We're getting closer, Luke!  Cloning directly into my modules folder got rid of the error.  Now, the mirror loads fine except that all I see is "Loading..." where the Nest is supposed to be displayed.

**Comment by mochman** [comment]
Yeah, all your added modules should go in the modules/ folder. 
This is a multi-nest error. I'll mess around with the code and see if I can let someone select which nest they want to use.

**Comment by mochman** [comment]
@brennn1 Okay, I updated the code for you to pull.  Now it will list out all of your thermostats.  You will then have to add  a line to your config.js to choose which thermostat you want to see.

**Comment by LoopyFoot** [comment]
Wow!  It works beautifully now.  I am thoroughly impressed with your level of support, and certainly incredibly appreciative!  For learning purposes, how did you modify the MMM-Nest.js Javascript code to fix this issue?

**Comment by mochman** [comment]
No worries.
The code originally took the temperature data from the first thermostat it saw.  It did this by setting the thermostat ID in a variable.  Since you had multiple thermostats, the variable was an array instead of a value.  The function didn't know what to do with that, so nothing happened.
The new function looks to see if there are multiple thermostats then lets the user pick one.  It then uses that number to choose the thermostat in the array for the rest of the program to get the correct data from.
You can see the edits [here](https://github.com/mochman/MMM-Nest/commit/ed4351c9b6202f77ee9ebc485c75d6b46212226b)

**Comment by LoopyFoot** [comment]
Is there a way to add text above a thermostat to say where it is located?  Can I modify the MMM-Nest.css to accomplish this?

**Comment by mochman** [comment]
I'm sure there is a way, but the easiest would be to just add a header to your config.js file

```
{
        module: 'MMM-Nest',
        header: 'NAME YOUR THERMOSTAT HERE'
        position: 'bottom_right',   
        config: {

            token: ...

            }
        },      
```

**Comment by mochman** [comment]
I just added that functionality without having to add the header.  Update to the latest version and take a look at the README.  It should be pretty straightforward.

**Comment by mochman** [comment]
I added a new display type for people who want to see all their thermostats at once.  Take a look and see if you like it.

**Comment by LoopyFoot** [comment]
Looks great!  I love the list display type!!  

One question - If I do not have a TargetTemp set on my Thermostat, it still displays a TargetTemp.  For example, when my thermostat is Off (with no target set), it still displays the previous target temperature that I had it set to.  Is there a way for it to display "Off" instead of the old target temp, when my thermostat is off?
