### ISSUE TITLE
Where is token displayed?

### ISSUE THREAD

**Issue by jamesrequa** [mochman/MMM-Nest#7]
I followed all instructions in the script getToken.sh inside Terminal. After inputing the PIN provided by Nest the terminal window closes and there isn't any Token displayed. Can you advise?

**Comment by mochman** [comment]
The script doesn't pause after it displays the token.  You need to stop your terminal from quitting after the script is complete.

**Comment by jamesrequa** [comment]
Thanks for the quick response. Sorry but how do I stop the terminal from quitting?

**Comment by mochman** [comment]
How are you running getToken.sh?  I usually just run it from the RasPi using putty.

**Comment by mochman** [comment]
You can also edit the script and add:
`read -n 1 -s`
at the bottom.  That'll wait for you to press a button before closing.

**Comment by jamesrequa** [comment]
I was running it directly from Terminal. I just tried via ssh and it worked! thanks
