### ISSUE TITLE
Feature Request for Fan

### ISSUE THREAD

**Issue by Sachin1968** [mochman/MMM-Nest#9]
Hello - Is it possible to incorporate the animated or even a static Fan icon in the display?

Thanks,
Sachin

**Comment by mochman** [comment]
Sure, give me a few days.  I'll probably add it just to the "Nest mode".

**Comment by mochman** [comment]
@Sachin1968 I just added the fan icon to the "Nest Display Mode".  I'm not good at CSS, so if it isn't positioned right, just edit the MMM-Nest.css file to your liking.

**Comment by Sachin1968** [comment]
Thanks. I'll give it a try today.

**Comment by mochman** [comment]
Is it working the way you wanted?
